# Copy to terraform.tfvars (gitignored) and edit. Nothing here is a secret --
# every credential in this stack is generated by Terraform and stored in
# Secrets Manager, never typed and never committed.

aws_profile = "fieldnation"     # must NOT be a work profile; preflight blocks known ones
region      = "ap-southeast-1"  # Singapore — closest region to Dhaka
sizing      = "minimal"         # minimal | production

# Lock the Kubernetes API to your own address. Find it with:
#   curl -s https://checkip.amazonaws.com
# public_access_cidrs = ["203.0.113.7/32"]

# Left at their destroyable defaults; flip all three for anything real.
# deletion_protection   = true
# skip_final_snapshot   = false
# force_destroy_buckets = false
